version: "1.0"
info:
  model: int-scaffold
packages:
- name: Prudhvi_EU_SuperIPaasProject
  gitServerName: prudhvi_Github
  gitUrl: https://github.com/prudhvi-penmetsa-saggs/Prudhvi_EU_SuperIPaasProject
  gitUsername: prudhvi-penmetsa-saggs
  gitBranch: master
- name: MFTDemo
  gitServerName: prudhvi_Github
  gitUrl: https://github.com/prudhvi-penmetsa-saggs
  gitUsername: prudhvi-penmetsa-saggs
  gitBranch: master
